"use client";

import Link from "next/link";
import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import MobileHeader from "@/components/layout/MobileHeader";
import { BottomSheetModal } from "@/components/modals";
import { deleteProviderOffer, getProviderOffers, getOwnedProviderInfo } from "../profile.service";
import type { ProviderOffer } from "../offer.types";

export function ProviderManageOffersScreen({ slug }: { slug: string }) {
  const [selected, setSelected] = useState<ProviderOffer | null>(null);
  const queryClient = useQueryClient();
  const query = useQuery({ queryKey: ["provider-offers", slug], queryFn: () => getProviderOffers(slug) });
  const provider = useQuery({ queryKey: ["providers", "mine", slug], queryFn: () => getOwnedProviderInfo(slug) });
  const remove = useMutation({ mutationFn: (id: string) => deleteProviderOffer(slug, id), onSuccess: async () => { setSelected(null); await queryClient.invalidateQueries({ queryKey: ["provider-offers", slug] }); } });
  return <div className="min-h-dvh bg-slate-50 pb-10"><MobileHeader title="Offers" subtitle={provider.data?.name ?? "Loading provider…"} /><main className="mx-auto w-full max-w-3xl px-page pt-5"><section className="mb-4 flex items-center justify-between rounded-2xl border border-slate-100 bg-white p-4"><div><p className="text-xs font-semibold text-foreground-muted">Total offers</p><p className="mt-1 text-2xl font-extrabold">{query.data?.length ?? 0}</p></div><Link href={`/${encodeURIComponent(slug)}/manage/offers/add`} className="flex h-10 items-center gap-1.5 rounded-xl bg-brand px-4 text-xs font-extrabold text-white"><i className="fa-solid fa-plus" />Add offer</Link></section>{query.isPending && <OfferSkeleton />}{query.isError && <div role="alert" className="rounded-2xl bg-red-50 p-4 text-sm text-danger">Couldn&apos;t load offers. <button type="button" onClick={() => void query.refetch()} className="font-extrabold underline">Try again</button></div>}{query.data?.length === 0 && <div className="rounded-2xl border border-dashed border-slate-200 bg-white p-7 text-center"><i className="fa-solid fa-tags text-2xl text-brand" /><p className="mt-3 text-sm font-extrabold">No offers found</p></div>}{query.data && query.data.length > 0 && <div className="overflow-hidden rounded-2xl border border-slate-100 bg-white">{query.data.map((offer) => <OfferRow key={offer.id} offer={offer} slug={slug} onDelete={() => setSelected(offer)} />)}</div>}</main><BottomSheetModal open={Boolean(selected)} onClose={() => !remove.isPending && setSelected(null)} title="Delete offer"><div className="px-page pb-[calc(env(safe-area-inset-bottom)+1.5rem)] pt-6"><h2 className="text-lg font-extrabold">Delete offer?</h2><p className="mt-2 text-sm text-foreground-muted">{selected?.title} will be permanently deleted.</p><div className="mt-6 grid grid-cols-2 gap-3"><button type="button" onClick={() => setSelected(null)} className="h-11 rounded-xl border border-slate-200 text-sm font-extrabold">Cancel</button><button type="button" disabled={remove.isPending} onClick={() => selected && remove.mutate(selected.id)} className="h-11 rounded-xl bg-danger text-sm font-extrabold text-white disabled:opacity-60">{remove.isPending ? "Deleting…" : "Delete"}</button></div></div></BottomSheetModal></div>;
}

function OfferRow({ offer, slug, onDelete }: { offer: ProviderOffer; slug: string; onDelete: () => void }) { return <article className="border-b border-slate-100 p-4 last:border-b-0"><div className="flex gap-3"><div className="flex size-16 shrink-0 items-center justify-center rounded-xl bg-brand-50 text-brand"><i className="fa-solid fa-tag" /></div><div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-2"><h2 className="truncate text-sm font-extrabold">{offer.title}</h2><span className={`rounded-full px-2 py-1 text-[10px] font-extrabold ${offer.is_currently_active ? "bg-emerald-50 text-emerald-700" : "bg-slate-100 text-slate-600"}`}>{humanize(offer.status)}</span></div><p className="mt-1 line-clamp-2 text-xs text-foreground-muted">{offer.description}</p><p className="mt-1 text-[10px] font-semibold text-foreground-muted">{formatDate(offer.starts_at)} – {formatDate(offer.expires_at)}</p></div></div><div className="mt-3 grid grid-cols-2 gap-2"><Link href={`/${encodeURIComponent(slug)}/manage/offers/${encodeURIComponent(offer.id)}/edit`} className="flex h-8 items-center justify-center gap-1.5 rounded-lg bg-brand-50 text-[11px] font-extrabold text-brand"><i className="fa-solid fa-pen" />Edit</Link><button type="button" onClick={onDelete} className="flex h-8 items-center justify-center gap-1.5 rounded-lg bg-red-50 text-[11px] font-extrabold text-danger"><i className="fa-solid fa-trash" />Delete</button></div></article>; }
function formatDate(value: string) { const date = new Date(value); return Number.isNaN(date.getTime()) ? value : new Intl.DateTimeFormat("en-IN", { dateStyle: "medium" }).format(date); }
function humanize(value: string) { return value.replaceAll("_", " ").replace(/\b\w/g, (letter) => letter.toUpperCase()); }
function OfferSkeleton() { return <div className="space-y-3 rounded-2xl bg-white p-4">{[0, 1, 2].map((item) => <div key={item} className="h-24 animate-pulse rounded-xl bg-slate-100" />)}</div>; }
