"use client";

import Link from "next/link";
import { useEffect, useMemo, useRef, useState } from "react";
import { useInfiniteQuery, useQuery } from "@tanstack/react-query";
import { LoaderCircle } from "lucide-react";
import axios from "axios";
import MobileHeader from "@/components/layout/MobileHeader";
import { BottomSheetModal } from "@/components/modals";
import { LocationButton } from "@/features/location";
import { useHydrated } from "@/lib/use-hydrated";
import { useAppSelector } from "@/store/hooks";
import { getProviderNameBySlug, getNearbyOffers } from "../provider.service";
import type { NearbyOffer } from "../provider.types";

export function NearbyOffersPage() {
  const hydrated = useHydrated();
  const { lat, lng, locality, city } = useAppSelector((state) => state.location);
  const [selectedOffer, setSelectedOffer] = useState<NearbyOffer | null>(null);
  const query = useInfiniteQuery({ queryKey: ["nearby-offers", lat, lng], queryFn: ({ pageParam }) => getNearbyOffers({ lat: lat!, lng: lng!, page: pageParam }), initialPageParam: 1, getNextPageParam: (page) => page.pagination.has_next ? page.pagination.page + 1 : undefined, enabled: hydrated && lat !== null && lng !== null });
  const offers = useMemo(() => query.data?.pages.flatMap((page) => page.results) ?? [], [query.data]);
  const loadMoreRef = useRef<HTMLDivElement>(null);
  const { fetchNextPage, hasNextPage, isFetchingNextPage } = query;
  useEffect(() => { const target = loadMoreRef.current; if (!target) return; const observer = new IntersectionObserver(([entry]) => { if (entry.isIntersecting && hasNextPage && !isFetchingNextPage) void fetchNextPage(); }, { rootMargin: "300px" }); observer.observe(target); return () => observer.disconnect(); }, [fetchNextPage, hasNextPage, isFetchingNextPage]);
  const error = axios.isAxiosError(query.error) ? query.error.response?.data?.detail ?? query.error.message : "Unable to load nearby offers.";
  return <div className="min-h-dvh bg-slate-50 pb-10"><MobileHeader title="Offers" subtitle={locality && city ? `Near ${locality}, ${city}` : "Offers near you"} /><main className="mx-auto w-full max-w-3xl px-page pt-5">{!hydrated ? <OfferSkeleton /> : lat === null || lng === null ? <div className="rounded-2xl border border-slate-100 bg-white p-7 text-center"><span className="mx-auto flex size-12 items-center justify-center rounded-full bg-brand-50 text-brand"><i className="fa-solid fa-location-dot" /></span><h2 className="mt-3 text-sm font-extrabold">Choose your location</h2><p className="mt-1 text-xs text-foreground-muted">Select an area to discover offers near you.</p><LocationButton className="mt-4 rounded-xl bg-brand px-5 py-2.5 text-sm font-bold text-white">Choose location</LocationButton></div> : query.isPending ? <OfferSkeleton /> : query.isError ? <div role="alert" className="rounded-2xl bg-red-50 p-5 text-center text-sm text-danger"><p>{String(error)}</p><button type="button" onClick={() => void query.refetch()} className="mt-3 font-extrabold underline">Try again</button></div> : offers.length === 0 ? <div className="rounded-2xl border border-dashed border-slate-200 bg-white p-8 text-center"><i className="fa-solid fa-tags text-2xl text-brand" /><h2 className="mt-3 text-sm font-extrabold">No nearby offers</h2><p className="mt-1 text-xs text-foreground-muted">Check again later for new deals.</p></div> : <div className="space-y-4">{offers.map((offer) => <OfferCard key={offer.id} offer={offer} onOpen={() => setSelectedOffer(offer)} />)}</div>}<div ref={loadMoreRef} className="flex h-20 items-center justify-center" aria-live="polite">{query.isFetchingNextPage && <><LoaderCircle size={20} className="animate-spin text-brand" /><span className="ml-2 text-sm font-semibold text-foreground-muted">Loading more</span></>}{!query.hasNextPage && offers.length > 0 && <span className="text-xs font-semibold text-foreground-subtle">You&apos;ve reached the end</span>}</div></main><OfferDetailsSheet offer={selectedOffer} onClose={() => setSelectedOffer(null)} /></div>;
}

function OfferCard({ offer, onOpen }: { offer: NearbyOffer; onOpen: () => void }) {
  const providerHref = `/${encodeURIComponent(offer.provider.slug)}`;
  const providerQuery = useQuery({ queryKey: ["provider", "offer-card", offer.provider.slug], queryFn: () => getProviderNameBySlug(offer.provider.slug) });
  const provider = providerQuery.data;
  const coordinates = provider?.location.coordinates;
  const address = provider ? [provider.location.address, provider.location.landmark, provider.location.locality, provider.location.city.name, provider.location.city.state, provider.location.postal_code].filter(Boolean).join(", ") : `${offer.provider.locality}, ${offer.provider.city.name}`;
  const directionsHref = coordinates && Number.isFinite(coordinates.latitude) && Number.isFinite(coordinates.longitude) ? `https://www.google.com/maps/dir/?api=1&destination=${coordinates.latitude},${coordinates.longitude}` : undefined;
  return <article role="button" tabIndex={0} onClick={onOpen} onKeyDown={(event) => { if (event.key === "Enter" || event.key === " ") { event.preventDefault(); onOpen(); } }} aria-label={`View offer details for ${offer.title}`} className="relative cursor-pointer overflow-hidden rounded-2xl border border-slate-100 bg-white p-4 shadow-[0_3px_12px_rgba(15,23,42,0.05)] transition-colors hover:border-brand-200 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-brand"><i className="fa-solid fa-tag pointer-events-none absolute -right-7 -top-7 -rotate-90 text-[7rem] text-brand opacity-10" aria-hidden="true" /><div className="relative flex items-start gap-3"><h2 className="min-w-0 flex-1 text-lg font-extrabold">{offer.title}</h2><i className="fa-solid fa-chevron-right mt-1 shrink-0 text-xs text-brand" aria-hidden="true" /></div><p className="relative mt-2 text-sm leading-5 text-foreground-muted">{offer.description}</p>{offer.terms.length > 0 && <ul className="relative mt-3 space-y-1.5">{offer.terms.slice(0, 2).map((term, index) => <li key={index} className="flex gap-2 text-xs text-foreground-muted"><i className="fa-solid fa-check mt-0.5 text-[10px] text-brand" />{term}</li>)}</ul>}<div className="relative mb-2 mt-4 space-y-1 text-xs font-extrabold text-brand"><p><i className="fa-solid fa-calendar-day mr-1.5" />Starts on {formatDate(offer.starts_at)}</p><p><i className="fa-solid fa-calendar-check mr-1.5" />Ends on {formatDate(offer.expires_at)}</p></div><section className="relative rounded-xl border border-slate-100 bg-slate-50 p-3"><Link href={providerHref} onClick={(event) => event.stopPropagation()} className="flex items-center gap-3"><span className="flex size-11 shrink-0 items-center justify-center overflow-hidden rounded-xl bg-brand-100 text-brand">{offer.provider.thumbnail ? <img src={offer.provider.thumbnail} alt="" className="size-full object-cover" /> : <i className="fa-solid fa-store" />}</span><span className="min-w-0 flex-1"><span className="block truncate text-sm font-extrabold">{offer.provider.name}</span><span className="mt-0.5 block truncate text-xs text-foreground-muted"><i className="fa-solid fa-location-dot mr-1 text-brand" />{address}</span></span><i className="fa-solid fa-chevron-right text-xs text-foreground-subtle" /></Link><div className="mt-3 grid grid-cols-3 gap-2" onClick={(event) => event.stopPropagation()}><ProviderAction href={provider?.contact.phone ? `tel:${provider.contact.phone}` : undefined} icon="fa-phone" label="Call" /><ProviderAction href={provider?.contact.whatsapp ? `https://wa.me/${provider.contact.whatsapp.replace(/\D/g, "")}` : undefined} icon="fa-whatsapp" label="WhatsApp" brand external /><ProviderAction href={directionsHref} icon="fa-diamond-turn-right" label="Direction" external /></div></section></article>;
}

function OfferDetailsSheet({ offer, onClose }: { offer: NearbyOffer | null; onClose: () => void }) {
  return <BottomSheetModal open={Boolean(offer)} onClose={onClose} title="Offer details" closeLabel="Close offer details">{offer && <div className="px-page pb-[calc(env(safe-area-inset-bottom)+1.5rem)] pt-5"><div className="flex items-start gap-3"><span className="flex size-11 shrink-0 items-center justify-center rounded-xl bg-brand-50 text-brand"><i className="fa-solid fa-tag" aria-hidden="true" /></span><h3 className="min-w-0 flex-1 text-xl font-extrabold text-foreground">{offer.title}</h3></div><p className="mt-4 whitespace-pre-line text-sm leading-6 text-foreground-muted">{offer.description}</p><div className="mt-4 space-y-1.5 text-sm"><p className="flex items-center gap-2 text-foreground"><i className="fa-solid fa-calendar-day w-4 text-center text-brand" aria-hidden="true" /><span className="font-extrabold">Valid from:</span><span className="font-semibold">{formatDate(offer.starts_at)}</span></p><p className="flex items-center gap-2 text-foreground"><i className="fa-solid fa-calendar-check w-4 text-center text-brand" aria-hidden="true" /><span className="font-extrabold">Valid until:</span><span className="font-semibold">{formatDate(offer.expires_at)}</span></p></div>{offer.terms.length > 0 && <div className="mt-5"><h4 className="text-sm font-extrabold text-foreground">Terms and conditions</h4><ul className="mt-3 space-y-2">{offer.terms.map((term, index) => <li key={index} className="flex gap-2 text-sm text-foreground-muted"><i className="fa-solid fa-check mt-1 text-[10px] text-brand" aria-hidden="true" /><span>{term}</span></li>)}</ul></div>}</div>}</BottomSheetModal>;
}
function ProviderAction({ href, icon, label, brand = false, external = false }: { href?: string; icon: string; label: string; brand?: boolean; external?: boolean }) { const className = "flex h-9 min-w-0 items-center justify-center gap-1 rounded-lg border border-brand-200 bg-white px-1 text-[10px] font-extrabold text-brand disabled:border-slate-200 disabled:text-slate-300"; return href ? <a href={href} target={external ? "_blank" : undefined} rel={external ? "noreferrer" : undefined} className={className}><i className={`${brand ? "fa-brands" : "fa-solid"} ${icon}`} /><span className="truncate">{label}</span></a> : <button type="button" disabled className={className}><i className={`${brand ? "fa-brands" : "fa-solid"} ${icon}`} /><span className="truncate">{label}</span></button>; }
function formatDate(value: string) { const date = new Date(value); return Number.isNaN(date.getTime()) ? value : new Intl.DateTimeFormat("en-IN", { dateStyle: "medium" }).format(date); }
function OfferSkeleton() { return <div className="space-y-4">{[0, 1, 2].map((item) => <div key={item} className="h-64 animate-pulse rounded-2xl bg-white" />)}</div>; }
